services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    env_file: ".env"
    environment:
      NODE_ENV: development
      DB_HOST: mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:3000
    depends_on:
      - mongo
    networks:
      - custom-network

  mongo:
    image: mongo:latest
    container_name: database-service
    ports:
      - ${DB_PORT}:27017
    volumes:
      - "./mongo_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - custom-network

volumes:
  mongo_data:

networks:
  custom-network:
    driver: bridge